# I did not put any dependency on the database here
# because I assumed to have a separate service for it
# adjust redis url to your needs
version: '3.7'
services:
  prod: &prod
    build:
      context: .
      dockerfile: ./path/to/Dockerfile-prod
      args:
        RUBY_VERSION: '2.5.3'
        BUNDLER_VERSION: '1.17.3'
        DB_PROD_HOST: '127.0.0.1'
    command: path/to/your/start/script
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      RAILS_ENV: production
      REDIS_URL: 'redis://redis:6379/0'
    network_mode: host
  redis:
    image: redis
